### ISSUE TITLE
Unresponsive Page

### ISSUE THREAD

**Issue by aiartsev** [DNNCommunity/DNN.Feedback#14] opened 2016-01-25 15:32 UTC
Hello,

I'm currently using this module as a Contact Form on a page with DNN 7.4.2, and whenever there is an error due to a required field being empty or the email not being correctly validated, all the hyperlinks on the page and the Send Feedback button become unresponsive. As a workaround, I've had to disable validation and make all the fields optional, but it'd be great to have this solved. Is this a known issue?

**Comment by EPTamminga** [comment] 2016-01-25 15:49
I have not heard this before. 
If possible, try to reproduce this on a clean DNN742 with the default standard DNN skin and a page with only the module on it.

**Comment by valadas** [comment] 2018-09-22 00:41
I cannot reproduce this issue, closing as a won't fix. Feel free to reopen if you have steps to reproduce this.

**Closed by valadas** 2018-09-22 00:41 UTC
Labels: Cannot reproduce
